version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome69 # runs tests using Chrome browser in custom executor (Cypress docker image)
          browser: chrome
          command: 'npm run test-ci'
